package com.example.repick.domain.user.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter @Setter @NoArgsConstructor
@DynamoDBTable(tableName = "userSmsVerificationInfo")
public class UserSmsVerificationInfo {

    @DynamoDBHashKey @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private Long userId;
    @DynamoDBAttribute
    private String phoneNumber;
    @DynamoDBAttribute
    private String verificationCode;
    @DynamoDBAttribute
    private Long expirationTime;

    @Builder
    public UserSmsVerificationInfo(String id, Long userId, String phoneNumber, String verificationCode, Long expirationTime) {
        this.id = id;
        this.userId = userId;
        this.phoneNumber = phoneNumber;
        this.verificationCode = verificationCode;
        this.expirationTime = expirationTime;
    }

}
