version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    overwrite: yes
permission:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: kill_process.sh
      timeout: 100
      runas: ec2-user
  ApplicationStart:
    - location: start_process.sh
      timeout: 3600
      runas: ec2-user