package com.example.repick.domain.announcement.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.example.repick.global.entity.BaseEntity;
import lombok.*;

@Getter @Setter @NoArgsConstructor @AllArgsConstructor
@DynamoDBTable(tableName = "announcement")
public class Announcement extends BaseEntity {

    @DynamoDBHashKey @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String content;

    @Builder
    public Announcement(String title, String content) {
        this.title = title;
        this.content = content;
    }

    public static Announcement of(String title, String content) {
        return Announcement.builder()
                .title(title)
                .content(content)
                .build();
    }
}
