name: Push to ECR

on:
  push:
    branches: [ "bug/cicd" ]

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: 654654448479.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: repick-repo
  IMAGE_TAG: 49119eb9a24649b0efd4bac3113fdb6655539606

permissions:
  contents: read

jobs:
  deploy:
    name: CD
    runs-on: ubuntu-latest

    steps:
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ env.AWS_REGION }}
#
#      - name: Login to Amazon ECR
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v2
#        with:
#          mask-password: true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.KEY }}
          script: |
#            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
#            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#            aws configure set region ${{ env.AWS_REGION }}
#            ECR_REGISTRY_LOGIN=$(aws ecr get-login-password --region ${{ env.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }})
            sudo docker stop dc
            sudo docker rm dc
            sudo docker pull ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            sudo docker run -d --name dc -p 8080:8080 ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}